USE [master]
GO
/****** Object:  Database [ORMMappers]    Script Date: 11-Apr-19 1:05:42 AM ******/
CREATE DATABASE [ORMMappers]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ORMMappers', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\ORMMappers.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ORMMappers_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\ORMMappers_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [ORMMappers] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ORMMappers].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ORMMappers] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ORMMappers] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ORMMappers] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ORMMappers] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ORMMappers] SET ARITHABORT OFF 
GO
ALTER DATABASE [ORMMappers] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ORMMappers] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ORMMappers] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ORMMappers] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ORMMappers] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ORMMappers] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ORMMappers] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ORMMappers] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ORMMappers] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ORMMappers] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ORMMappers] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ORMMappers] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ORMMappers] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ORMMappers] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ORMMappers] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ORMMappers] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ORMMappers] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ORMMappers] SET RECOVERY FULL 
GO
ALTER DATABASE [ORMMappers] SET  MULTI_USER 
GO
ALTER DATABASE [ORMMappers] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ORMMappers] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ORMMappers] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ORMMappers] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ORMMappers] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'ORMMappers', N'ON'
GO
ALTER DATABASE [ORMMappers] SET QUERY_STORE = OFF
GO
USE [ORMMappers]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [ORMMappers]
GO
/****** Object:  Table [dbo].[Course]    Script Date: 11-Apr-19 1:05:42 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Course](
	[Course_ID] [int] IDENTITY(1,1) NOT NULL,
	[CourseName] [nvarchar](50) NOT NULL,
	[CourseDescription] [nvarchar](50) NOT NULL,
	[CourseContents] [nvarchar](500) NOT NULL,
	[CourseDuration] [int] NOT NULL,
 CONSTRAINT [PK_Course] PRIMARY KEY CLUSTERED 
(
	[Course_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Intake]    Script Date: 11-Apr-19 1:05:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Intake](
	[Intake_ID] [int] IDENTITY(1,1) NOT NULL,
	[StartDate] [datetime] NOT NULL,
	[EndDate] [datetime] NOT NULL,
	[Times] [nvarchar](150) NOT NULL,
	[Course_ID] [int] NOT NULL,
	[Price] [float] NOT NULL,
 CONSTRAINT [PK_Intakes] PRIMARY KEY CLUSTERED 
(
	[Intake_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Student]    Script Date: 11-Apr-19 1:05:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Student](
	[Student_ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NULL,
	[EMail] [nvarchar](50) NULL,
	[Mobile] [nvarchar](50) NULL,
	[Address] [nvarchar](50) NULL,
	[Gender] [nvarchar](50) NULL,
 CONSTRAINT [PK_Student] PRIMARY KEY CLUSTERED 
(
	[Student_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [ORMMappers] SET  READ_WRITE 
GO
